#!/bin/bash

set -e

############################
## Setup required for zsh ##
############################

echo "> Setting up zsh"

ZINIT=$HOME/.zinit

if [[ ! -d $ZINIT ]]; then
    echo "~ Installing :: zinit"

    command mkdir -p $ZINIT && command chmod g-rwX $ZINIT
    command git clone https://github.com/zdharma/zinit "$ZINIT/bin" && \
        echo "+ Done" || \
        echo "- Fail"

    echo "~ All 'zinit' plugins will be installed on first prompt."
else
    echo "~ Already Installed :: zinit"
    echo "~ Run 'zinit self-update && zinit update --all' to update plugins"
fi

find_zsh() {
	if command -v zsh >/dev/null 2>&1 && grep "$(command -v zsh)" /etc/shells >/dev/null; then
		command -v zsh
	else
		echo "/bin/zsh"
	fi
}

zsh="$(find_zsh)"

echo "> Setting 'zsh' as default shell"

test "$(expr "$SHELL" : '.*/\(.*\)')" != "zsh" &&
	command -v chsh >/dev/null 2>&1 &&
	chsh -s "$zsh" &&
	echo "> Set $("$zsh" --version) at $zsh as your default shell"

success '>> All installed! Enjoy dofiles :) <<'
