#!/bin/zsh

### Added by Zinit's installer
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
    print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{220} Initiative Plugin Manager (%F{33}zdharma/zinit%F{220})…%f"
    command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
    command git clone https://github.com/zdharma/zinit "$HOME/.zinit/bin" && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
        print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit
### End of Zinit's installer chunk

# Load .zsh_pre if available
zinit is-snippet for if"[[ -f $HOME/.zsh_pre ]]" $HOME/.zsh_pre

############
# DOTFILES #
############
export DOTFILES=${DOTFILES:=$HOME/.dotfiles}
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:=$HOME/.config}
export TERM=${TERM:=screen-256color}
export COLORTERM=${COLORTERM:=truecolor}
# fixed powerline fonts rendering inside tmux
export LC_ALL=en_IN.UTF-8
export LANG=en_IN.UTF-8

#####################
# PROMPT            #
#####################
zinit lucid for \
    as"command" from"gh-r" atload'eval "$(starship init zsh)"' bpick'*unknown-linux-gnu*' \
    starship/starship \

##########################
# OMZ Libs and Plugins   #
##########################

# IMPORTANT:
# Ohmyzsh plugins and libs are loaded first as some these sets some defaults which are required later on.
# Otherwise something will look messed up
# ie. some settings help zsh-autosuggestions to clear after tab completion

setopt promptsubst

# Explanation:
# - Loading tmux first, to prevent jumps when tmux is loaded after .zshrc
# - History plugin is loaded early (as it has some defaults) to prevent empty history stack for other plugins
zinit lucid for \
    atinit"
        export ZSH_TMUX_FIXTERM=false
        export ZSH_TMUX_AUTOSTART=true
        export ZSH_TMUX_AUTOCONNECT=true
        export ZSH_TMUX_DEFAULT_SESSION_NAME='</>'
    " \
    https://gist.githubusercontent.com/numToStr/eb8f0d74cca69646df7cdfc773f855c8/raw/6bf87b70b9a0808a5fa29475140904a4487bde8f/tmux.plugin.zsh \
    atinit"HIST_STAMPS=dd.mm.yyyy" \
    OMZL::history.zsh \


zinit wait lucid for \
	OMZL::clipboard.zsh \
	OMZL::compfix.zsh \
	OMZL::completion.zsh \
	OMZL::correction.zsh \
    atload'
        alias ..="cd .."
        alias ...="cd ../.."
        alias ....="cd ../../.."
        alias .....="cd ../../../.."

        function take() {
            mkdir -p $@ && cd ${@:$#}
        }

        alias rm="rm -rf"
    ' \
	OMZL::directories.zsh \
	OMZL::git.zsh \
	OMZL::grep.zsh \
	OMZL::key-bindings.zsh \
	OMZL::spectrum.zsh \
	OMZL::termsupport.zsh \
    atload"
        alias gcd='git checkout dev'
        alias gce='git commit -a -e'
    " \
	OMZP::git \
	OMZP::docker-compose \
	as"completion" OMZP::docker/_docker \
    djui/alias-tips \
    https://github.com/junegunn/fzf/blob/master/shell/key-bindings.zsh \
    https://github.com/junegunn/fzf/blob/master/shell/completion.zsh \
    # hlissner/zsh-autopair \
    # chriskempson/base16-shell \
	# OMZP::fzf \

#####################
# PLUGINS           #
#####################
# @source: https://github.com/crivotz/dot_files/blob/master/linux/zplugin/zshrc

# IMPORTANT:
# These plugins should be loaded after ohmyzsh plugins

zinit wait lucid for \
    light-mode blockf atpull'zinit creinstall -q .' \
    atinit"
        zstyle ':completion:*' completer _expand _complete _ignored _approximate
        zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
        zstyle ':completion:*' menu select=2
        zstyle ':completion:*' select-prompt '%SScrolling active: current selection at %p%s'
        zstyle ':completion:*:descriptions' format '-- %d --'
        zstyle ':completion:*:processes' command 'ps -au$USER'
        zstyle ':completion:complete:*:options' sort false
        zstyle ':fzf-tab:complete:_zlua:*' query-string input
        zstyle ':completion:*:*:*:*:processes' command 'ps -u $USER -o pid,user,comm,cmd -w -w'
        zstyle ':fzf-tab:complete:kill:argument-rest' extra-opts --preview=$extract'ps --pid=$in[(w)1] -o cmd --no-headers -w -w' --preview-window=down:3:wrap
        zstyle ':fzf-tab:complete:cd:*' extra-opts --preview=$extract'exa -1 --color=always ${~ctxt[hpre]}$in'
    " \
        zsh-users/zsh-completions \
    light-mode atinit"ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20" atload"_zsh_autosuggest_start" \
        zsh-users/zsh-autosuggestions \
    light-mode atinit"
        typeset -gA FAST_HIGHLIGHT;
        FAST_HIGHLIGHT[git-cmsg-len]=100;
        zpcompinit;
        zpcdreplay;
    " \
        zdharma/fast-syntax-highlighting \
    bindmap"^R -> ^H" atinit"
        zstyle :history-search-multi-word page-size 10
        zstyle :history-search-multi-word highlight-color fg=red,bold
        zstyle :plugin:history-search-multi-word reset-prompt-protect 1
    " \
        zdharma/history-search-multi-word \
    reset \
    atclone"local P=${${(M)OSTYPE:#*darwin*}:+g}
            \${P}sed -i \
            '/DIR/c\DIR 38;5;63;1' LS_COLORS; \
            \${P}dircolors -b LS_COLORS > c.zsh" \
    atpull'%atclone' pick"c.zsh" nocompile'!' \
    atload'zstyle ":completion:*" list-colors “${(s.:.)LS_COLORS}”' \
        trapd00r/LS_COLORS


#####################
# PROGRAMS          #
#####################

zinit wait lucid light-mode as'command' for \
    from'gh-r' atinit'export PATH="$HOME/.yarn/bin:$PATH"' mv'yarn* -> yarn' pick"yarn/bin/yarn" bpick'*.tar.gz' \
        yarnpkg/yarn \

zinit wait"1a" lucid light-mode from"gh-r" as"command" bpick'*linux*' for \
     atload'
        eval "$(snm env zsh)"
        alias n="snm"
    ' mv'snm* -> snm' pick'snm/snm' \
        @numToStr/snm \
    atload'
        eval "$(zoxide init --no-aliases zsh)"
        alias z="__zoxide_z"
    ' mv'zoxide* -> zoxide' pick'zoxide/zoxide' \
        @ajeetdsouza/zoxide \
        @junegunn/fzf \
    mv'ripgrep* -> rg' pick'rg/rg' \
        @BurntSushi/ripgrep \
    mv'fd* -> fd' pick'fd/fd' \
        @sharkdp/fd \
    mv'bat* -> bat' pick'bat/bat' \
        @sharkdp/bat \
    mv'delta* -> delta' pick'delta/delta' \
        @dandavison/delta \
    atload'
        unalias l
        alias l="exa -abghHlS --git --group-directories-first"
    ' pick'bin/exa' \
        @ogham/exa \
    # mv'vivid* -> vivid' pick'vivid/vivid' atload'export LS_COLORS="$(vivid generate ayu)"' \
    #     @sharkdp/vivid \

# atclone'
#         mkdir -p $HOME/.config/nvim/plugin
#         curl https://raw.githubusercontent.com/junegunn/fzf/master/plugin/fzf.vim -o $HOME/.config/nvim/plugin/fzf.vim
#     ' atpull'%atclone'

#####################
# MANUAL CONFIG     #
#####################

# 1. Load all .zsh files under zsh/.dotrc directory
# 3. Load ~/.localrc, if it exists
# 3. Load ~/.zsh_post if it exists
zinit wait'0a' lucid is-snippet for \
    $HOME/.dotrc/*.zsh \
    if"[[ -f $HOME/.localrc  ]]" $HOME/.localrc \
    if"[[ -f $HOME/.zsh_post ]]" $HOME/.zsh_post
